### ISSUE TITLE
Can't run example code on the command line

### ISSUE THREAD

**Issue by notwaldorf** [abey79/hatched#11]
Using the `skull.png` file, I run `vpype hatched --levels 20 100 180 -p 5 -b 1 skull.png write hatched.svg` and get

```
Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
WARNING:root:no geometry to save, no file created
```

I'm on an M1 mac and my install is a bit messed up ('vpype show' doesn't work), but I wouldn't have thought it affected anything other than the fancy `show`.

**Comment by abey79** [comment]
Hello @notwaldorf, thanks a lot for the feedback. It should be fixed now.

**Comment by abey79** [comment]
BTW @notwaldorf, are you aware of the updated M1 install instructions [here](https://vpype.readthedocs.io/en/latest/install.html#macos-apple-silicon-m1)? They involve a few more steps than I would like but they do work properly (I'm a M1 owner as well).

**Comment by notwaldorf** [comment]
Thanks so much for the fix!

Yeah, I followed the new instructions, but I have homebrew instead of ports and there’s something whack going on with one of the dependencies. I get the same resolution conflict as [here](https://github.com/abey79/vpype/issues/320#issuecomment-1039317573) despite doing all the right things, so I just gave up on the fancy `show` for now 😅. No worries, writing to files is my jam anyway.

(thank you so much for making vpype, it’s an absolute gem!!!)

**Comment by abey79** [comment]
Yeah I'm not sure why Homebrew causes so much problems. I've had quite an history with that, which is why I always encourage people to try MacPorts. I personally find it superior and it's totally non-intrusive since everything gets installed in `/opt/local`. Just delete the whole thing if you don't like it :)

> (thank you so much for making vpype, it’s an absolute gem!!!)

Much appreciated 🙏🏻  I'm glad you find it useful! (Do watch for the upcoming 1.9 release -- it's gonna be pretty big.)
